e:\Python27\python.exe PushRetrieveData.py 0
copy newhot_content_list.xml Instance1\
copy newhot_content_list.xml Instance2\
copy newhot_content_list.xml Instance3\
copy newhot_content_list.xml Instance4\
copy newupload_content_list.xml Instance1\
copy newupload_content_list.xml Instance2\
copy newupload_content_list.xml Instance3\
copy newupload_content_list.xml Instance4\
